/**
 * Curated Top Amazon.de departments / high-demand shopping categories.
 * `amazonCategoryId` matches RapidAPI `/product-category-list` IDs for DE.
 * Used as deterministic fallback when the live category list is unavailable.
 */
export type TopCategorySeed = {
  slug: string;
  amazonCategoryId: string;
  nameDe: string;
  nameEn: string;
  descriptionDe: string;
  descriptionEn: string;
  searchKeywords: string[];
};

/** Categories that are poor fits for comparison/affiliate product sync. */
export const AMAZON_CATEGORY_DENYLIST = new Set([
  "aps",
  "alexa-skills",
  "amazon-devices",
  "amazon-global-store",
  "audible",
  "digital-music",
  "digital-text",
  "gift-cards",
  "magazines",
  "mobile-apps",
  "prime-exclusive",
  "subscribe-with-amazon",
  "warehouse-deals",
  "amazon-warehouse",
  "pantry",
  "luxury-beauty",
  "under-ten-dollars",
  "local-services",
  "collectibles",
  "coins",
  "courses",
  "aws-courses",
]);

export const AMAZON_TOP_CATEGORIES_DE: TopCategorySeed[] = [
  {
    slug: "elektronik",
    amazonCategoryId: "electronics",
    nameDe: "Elektronik",
    nameEn: "Electronics",
    descriptionDe:
      "Vergleich aktueller Elektronik-Bestseller – Technik, Preis und Nutzerbewertungen.",
    descriptionEn:
      "Compare current electronics bestsellers by specs, price and ratings.",
    searchKeywords: ["elektronik bestseller", "electronics"],
  },
  {
    slug: "computer-zubehoer",
    amazonCategoryId: "computers",
    nameDe: "Computer & Zubehör",
    nameEn: "Computers & Accessories",
    descriptionDe:
      "Computer, Laptops und Zubehör im Vergleich für Alltag und Homeoffice.",
    descriptionEn:
      "Computers, laptops and accessories compared for everyday and remote work.",
    searchKeywords: ["computer zubehör", "laptop"],
  },
  {
    slug: "heimkino-tv",
    amazonCategoryId: "electronics",
    nameDe: "Heimkino & TV",
    nameEn: "Home Cinema & TV",
    descriptionDe: "TVs, Soundbars und Heimkino-Technik im direkten Vergleich.",
    descriptionEn: "TVs, soundbars and home cinema gear compared side by side.",
    searchKeywords: ["fernseher 4k", "soundbar"],
  },
  {
    slug: "smartphones",
    amazonCategoryId: "electronics",
    nameDe: "Smartphones",
    nameEn: "Smartphones",
    descriptionDe: "Aktuelle Smartphones nach Preis-Leistung und Ausstattung.",
    descriptionEn: "Current smartphones by value and feature set.",
    searchKeywords: ["smartphone", "handy"],
  },
  {
    slug: "kopfhoerer-audio",
    amazonCategoryId: "electronics",
    nameDe: "Kopfhörer & Audio",
    nameEn: "Headphones & Audio",
    descriptionDe: "Kopfhörer, Earbuds und Lautsprecher für Alltag und Sport.",
    descriptionEn: "Headphones, earbuds and speakers for daily use and sport.",
    searchKeywords: ["bluetooth kopfhörer", "earbuds"],
  },
  {
    slug: "haushalt-kueche",
    amazonCategoryId: "kitchen",
    nameDe: "Haushalt & Küche",
    nameEn: "Home & Kitchen",
    descriptionDe: "Küchengeräte und Haushaltshelfer mit starker Preis-Leistung.",
    descriptionEn: "Kitchen appliances and household helpers with strong value.",
    searchKeywords: ["küchengeräte", "haushaltshelfer"],
  },
  {
    slug: "staubsauger",
    amazonCategoryId: "kitchen",
    nameDe: "Staubsauger",
    nameEn: "Vacuum Cleaners",
    descriptionDe: "Akku-, Boden- und Roboterstaubsauger im Vergleich.",
    descriptionEn: "Cordless, canister and robot vacuums compared.",
    searchKeywords: ["akku staubsauger", "roboterstaubsauger"],
  },
  {
    slug: "kaffeemaschinen",
    amazonCategoryId: "kitchen",
    nameDe: "Kaffeemaschinen",
    nameEn: "Coffee Machines",
    descriptionDe: "Vollautomaten, Pads und Filterkaffeemaschinen im Check.",
    descriptionEn: "Bean-to-cup, pod and filter coffee machines reviewed.",
    searchKeywords: ["kaffeevollautomat", "kaffeemaschine"],
  },
  {
    slug: "heimwerker",
    amazonCategoryId: "diy",
    nameDe: "Heimwerker & Werkzeug",
    nameEn: "DIY & Tools",
    descriptionDe: "Werkzeuge und Heimwerker-Equipment für Garage und Werkstatt.",
    descriptionEn: "Tools and DIY gear for garage and workshop projects.",
    searchKeywords: ["akkuschrauber", "werkzeug"],
  },
  {
    slug: "garten",
    amazonCategoryId: "garden",
    nameDe: "Garten",
    nameEn: "Garden",
    descriptionDe: "Gartengeräte, Möbel und Pflegeprodukte im Vergleich.",
    descriptionEn: "Garden tools, furniture and care products compared.",
    searchKeywords: ["gartengeräte", "rasenmäher"],
  },
  {
    slug: "sport-outdoor",
    amazonCategoryId: "sports",
    nameDe: "Sport & Outdoor",
    nameEn: "Sports & Outdoors",
    descriptionDe: "Fitness-, Outdoor- und Sportausrüstung für aktive Nutzung.",
    descriptionEn: "Fitness, outdoor and sports gear for active use.",
    searchKeywords: ["fitnessgeräte", "outdoor ausrüstung"],
  },
  {
    slug: "fitness",
    amazonCategoryId: "sports",
    nameDe: "Fitness",
    nameEn: "Fitness",
    descriptionDe: "Hanteln, Matten und Smart-Fitness-Gadgets im Vergleich.",
    descriptionEn: "Weights, mats and smart fitness gadgets compared.",
    searchKeywords: ["hanteln set", "yogamatte"],
  },
  {
    slug: "mode",
    amazonCategoryId: "fashion",
    nameDe: "Mode",
    nameEn: "Fashion",
    descriptionDe: "Beliebte Mode-Basics und Accessoires im Überblick.",
    descriptionEn: "Popular fashion basics and accessories at a glance.",
    searchKeywords: ["mode damen", "mode herren"],
  },
  {
    slug: "schuhe",
    amazonCategoryId: "shoes",
    nameDe: "Schuhe",
    nameEn: "Shoes",
    descriptionDe: "Lauf-, Freizeit- und Alltagsschuhe nach Komfort und Preis.",
    descriptionEn: "Running, casual and everyday shoes by comfort and price.",
    searchKeywords: ["laufschuhe", "sneakers"],
  },
  {
    slug: "uhren",
    amazonCategoryId: "watches",
    nameDe: "Uhren",
    nameEn: "Watches",
    descriptionDe: "Smartwatches und Armbanduhren im direkten Vergleich.",
    descriptionEn: "Smartwatches and wristwatches compared side by side.",
    searchKeywords: ["smartwatch", "armbanduhr"],
  },
  {
    slug: "schoenheit",
    amazonCategoryId: "beauty",
    nameDe: "Beauty & Pflege",
    nameEn: "Beauty & Personal Care",
    descriptionDe: "Pflege-, Styling- und Beauty-Geräte mit starker Nachfrage.",
    descriptionEn: "Care, styling and beauty devices with strong demand.",
    searchKeywords: ["haartrockner", "rasierer"],
  },
  {
    slug: "drogerie",
    amazonCategoryId: "drugstore",
    nameDe: "Drogerie & Körperpflege",
    nameEn: "Drugstore & Body Care",
    descriptionDe: "Körperpflege und Drogerie-Bestseller im Vergleich.",
    descriptionEn: "Body care and drugstore bestsellers compared.",
    searchKeywords: ["körperpflege", "zahnbürste elektrisch"],
  },
  {
    slug: "baby",
    amazonCategoryId: "baby",
    nameDe: "Baby",
    nameEn: "Baby",
    descriptionDe: "Babyprodukte für Alltag, Pflege und unterwegs.",
    descriptionEn: "Baby products for daily care and on the go.",
    searchKeywords: ["babyphone", "kinderwagen"],
  },
  {
    slug: "spielzeug",
    amazonCategoryId: "toys",
    nameDe: "Spielzeug",
    nameEn: "Toys",
    descriptionDe: "Beliebte Spielzeuge und Lernprodukte im Überblick.",
    descriptionEn: "Popular toys and learning products overview.",
    searchKeywords: ["spielzeug kinder", "lego"],
  },
  {
    slug: "auto-motorrad",
    amazonCategoryId: "automotive",
    nameDe: "Auto & Motorrad",
    nameEn: "Automotive",
    descriptionDe: "Kfz-Zubehör und Pflegeprodukte für Auto und Motorrad.",
    descriptionEn: "Car and motorcycle accessories and care products.",
    searchKeywords: ["auto zubehör", "dashcam"],
  },
  {
    slug: "haustier",
    amazonCategoryId: "pet-supplies",
    nameDe: "Haustier",
    nameEn: "Pet Supplies",
    descriptionDe: "Futter, Zubehör und Pflege für Hunde, Katzen und mehr.",
    descriptionEn: "Food, accessories and care for dogs, cats and more.",
    searchKeywords: ["hundebett", "katzenstreu"],
  },
  {
    slug: "buero",
    amazonCategoryId: "office-products",
    nameDe: "Bürobedarf",
    nameEn: "Office Products",
    descriptionDe: "Drucker, Stühle und Bürohelfer für produktives Arbeiten.",
    descriptionEn: "Printers, chairs and office helpers for productive work.",
    searchKeywords: ["bürostuhl", "drucker"],
  },
  {
    slug: "beleuchtung",
    amazonCategoryId: "lighting",
    nameDe: "Beleuchtung",
    nameEn: "Lighting",
    descriptionDe: "Lampen, LED und smarte Beleuchtung im Vergleich.",
    descriptionEn: "Lamps, LED and smart lighting compared.",
    searchKeywords: ["led lampe", "deckenlampe"],
  },
  {
    slug: "moebel",
    amazonCategoryId: "furniture",
    nameDe: "Möbel",
    nameEn: "Furniture",
    descriptionDe: "Möbel für Wohnen, Schlafen und Homeoffice.",
    descriptionEn: "Furniture for living, sleeping and home office.",
    searchKeywords: ["schreibtisch", "regal"],
  },
  {
    slug: "heimtextilien",
    amazonCategoryId: "home-garden",
    nameDe: "Heimtextilien",
    nameEn: "Home Textiles",
    descriptionDe: "Bettwäsche, Handtücher und Wohnaccessoires im Check.",
    descriptionEn: "Bedding, towels and home accessories checked.",
    searchKeywords: ["bettwäsche", "handtücher"],
  },
  {
    slug: "koffer-reisen",
    amazonCategoryId: "luggage",
    nameDe: "Koffer & Reisen",
    nameEn: "Luggage & Travel",
    descriptionDe: "Koffer, Rucksäcke und Reisezubehör im Vergleich.",
    descriptionEn: "Suitcases, backpacks and travel accessories compared.",
    searchKeywords: ["koffer", "reiserucksack"],
  },
  {
    slug: "kameras",
    amazonCategoryId: "electronics",
    nameDe: "Kameras & Foto",
    nameEn: "Cameras & Photo",
    descriptionDe: "Kameras, Objektive und Fotozubehör für Einsteiger und Profis.",
    descriptionEn: "Cameras, lenses and photo gear for beginners and pros.",
    searchKeywords: ["digitalkamera", "action cam"],
  },
  {
    slug: "gaming",
    amazonCategoryId: "videogames",
    nameDe: "Gaming",
    nameEn: "Gaming",
    descriptionDe: "Konsolen, Controllers und Gaming-Zubehör im Vergleich.",
    descriptionEn: "Consoles, controllers and gaming accessories compared.",
    searchKeywords: ["gaming headset", "controller"],
  },
  {
    slug: "musikinstrumente",
    amazonCategoryId: "musical-instruments",
    nameDe: "Musikinstrumente",
    nameEn: "Musical Instruments",
    descriptionDe: "Instrumente und Audio-Equipment für Einsteiger und Hobby.",
    descriptionEn: "Instruments and audio gear for beginners and hobbyists.",
    searchKeywords: ["gitarre", "keyboard"],
  },
  {
    slug: "industrie-wissenschaft",
    amazonCategoryId: "industrial",
    nameDe: "Gewerbe & Industrie",
    nameEn: "Industrial & Scientific",
    descriptionDe: "Technik und Ausrüstung für Werkstatt und Gewerbe.",
    descriptionEn: "Gear and equipment for workshop and business use.",
    searchKeywords: ["messgerät", "schutzausrüstung"],
  },
  {
    slug: "grossgeraete",
    amazonCategoryId: "appliances",
    nameDe: "Haushaltsgroßgeräte",
    nameEn: "Major Appliances",
    descriptionDe: "Waschmaschinen, Kühlschränke und Großgeräte im Vergleich.",
    descriptionEn: "Washing machines, fridges and major appliances compared.",
    searchKeywords: ["waschmaschine", "kühlschrank"],
  },
  {
    slug: "klima-heizung",
    amazonCategoryId: "appliances",
    nameDe: "Klima & Heizung",
    nameEn: "Climate & Heating",
    descriptionDe: "Ventilatoren, Klimageräte und Heizlüfter im Alltagstest.",
    descriptionEn: "Fans, AC units and heaters for everyday use.",
    searchKeywords: ["klimaanlage mobil", "heizlüfter"],
  },
  {
    slug: "smart-home",
    amazonCategoryId: "electronics",
    nameDe: "Smart Home",
    nameEn: "Smart Home",
    descriptionDe: "Smarte Steckdosen, Kameras und Assistenten im Vergleich.",
    descriptionEn: "Smart plugs, cameras and assistants compared.",
    searchKeywords: ["smart home", "überwachungskamera"],
  },
  {
    slug: "tablets-ebooks",
    amazonCategoryId: "electronics",
    nameDe: "Tablets & E-Reader",
    nameEn: "Tablets & E-Readers",
    descriptionDe: "Tablets und E-Reader für Lesen, Streaming und Arbeiten.",
    descriptionEn: "Tablets and e-readers for reading, streaming and work.",
    searchKeywords: ["tablet", "e-reader"],
  },
  {
    slug: "drucker-scanner",
    amazonCategoryId: "computers",
    nameDe: "Drucker & Scanner",
    nameEn: "Printers & Scanners",
    descriptionDe: "Multifunktionsdrucker und Scanner für Homeoffice.",
    descriptionEn: "Multifunction printers and scanners for home office.",
    searchKeywords: ["drucker multifunktion", "scanner"],
  },
  {
    slug: "monitore",
    amazonCategoryId: "computers",
    nameDe: "Monitore",
    nameEn: "Monitors",
    descriptionDe: "Büro- und Gaming-Monitore nach Auflösung und Ergonomie.",
    descriptionEn: "Office and gaming monitors by resolution and ergonomics.",
    searchKeywords: ["monitor 27 zoll", "gaming monitor"],
  },
  {
    slug: "netzwerk",
    amazonCategoryId: "computers",
    nameDe: "Netzwerk & WLAN",
    nameEn: "Networking & Wi‑Fi",
    descriptionDe: "Router, Mesh-Systeme und Repeater im Vergleich.",
    descriptionEn: "Routers, mesh systems and repeaters compared.",
    searchKeywords: ["wlan router", "mesh wlan"],
  },
  {
    slug: "speichermedien",
    amazonCategoryId: "computers",
    nameDe: "Speicher & Festplatten",
    nameEn: "Storage & Drives",
    descriptionDe: "SSDs, externe Festplatten und USB-Sticks im Check.",
    descriptionEn: "SSDs, external drives and USB sticks checked.",
    searchKeywords: ["ssd 1tb", "externe festplatte"],
  },
  {
    slug: "pc-peripherie",
    amazonCategoryId: "computers",
    nameDe: "PC-Peripherie",
    nameEn: "PC Peripherals",
    descriptionDe: "Tastaturen, Mäuse und Webcams für produktives Arbeiten.",
    descriptionEn: "Keyboards, mice and webcams for productive work.",
    searchKeywords: ["tastatur", "gaming maus"],
  },
  {
    slug: "powerbanks",
    amazonCategoryId: "electronics",
    nameDe: "Powerbanks & Akkus",
    nameEn: "Power Banks & Batteries",
    descriptionDe: "Powerbanks und Ladegeräte für unterwegs.",
    descriptionEn: "Power banks and chargers for on the go.",
    searchKeywords: ["powerbank", "usb c ladegerät"],
  },
  {
    slug: "wearables",
    amazonCategoryId: "electronics",
    nameDe: "Wearables",
    nameEn: "Wearables",
    descriptionDe: "Fitness-Tracker und Wearables für Gesundheit und Sport.",
    descriptionEn: "Fitness trackers and wearables for health and sport.",
    searchKeywords: ["fitness tracker", "smartwatch sport"],
  },
  {
    slug: "grill-outdoor-kueche",
    amazonCategoryId: "garden",
    nameDe: "Grill & Outdoor-Küche",
    nameEn: "Grill & Outdoor Kitchen",
    descriptionDe: "Grills und Outdoor-Küchenzubehör für die Saison.",
    descriptionEn: "Grills and outdoor kitchen accessories for the season.",
    searchKeywords: ["gasgrill", "elektrogrill"],
  },
  {
    slug: "camping",
    amazonCategoryId: "sports",
    nameDe: "Camping",
    nameEn: "Camping",
    descriptionDe: "Zelte, Isomatten und Camping-Kochausrüstung im Vergleich.",
    descriptionEn: "Tents, sleeping pads and camping cookware compared.",
    searchKeywords: ["zelt 3 personen", "camping kocher"],
  },
  {
    slug: "fahrrad",
    amazonCategoryId: "sports",
    nameDe: "Fahrrad & E-Bike Zubehör",
    nameEn: "Bike & E-Bike Accessories",
    descriptionDe: "Fahrradhelme, Schlösser und E-Bike-Zubehör im Check.",
    descriptionEn: "Bike helmets, locks and e-bike accessories checked.",
    searchKeywords: ["fahrradhelm", "fahrradschloss"],
  },
  {
    slug: "schmuck",
    amazonCategoryId: "jewelry",
    nameDe: "Schmuck",
    nameEn: "Jewelry",
    descriptionDe: "Beliebte Schmuckstücke und Accessoires im Überblick.",
    descriptionEn: "Popular jewelry and accessories at a glance.",
    searchKeywords: ["halskette", "ohrringe"],
  },
  {
    slug: "rucksacke-taschen",
    amazonCategoryId: "luggage",
    nameDe: "Rucksäcke & Taschen",
    nameEn: "Backpacks & Bags",
    descriptionDe: "Alltagsrucksäcke, Laptoptaschen und City-Bags im Vergleich.",
    descriptionEn: "Everyday backpacks, laptop bags and city bags compared.",
    searchKeywords: ["rucksack laptop", "umhängetasche"],
  },
  {
    slug: "reinigung",
    amazonCategoryId: "kitchen",
    nameDe: "Reinigung",
    nameEn: "Cleaning",
    descriptionDe: "Putzhelfer, Wischsysteme und Reinigungsgeräte im Alltag.",
    descriptionEn: "Cleaning helpers, mops and cleaning devices for daily use.",
    searchKeywords: ["wischmopp", "fenstersauger"],
  },
  {
    slug: "luftreiniger",
    amazonCategoryId: "appliances",
    nameDe: "Luftreiniger & Luftbefeuchter",
    nameEn: "Air Purifiers & Humidifiers",
    descriptionDe: "Luftreiniger und Luftbefeuchter für ein besseres Raumklima.",
    descriptionEn: "Air purifiers and humidifiers for better indoor air.",
    searchKeywords: ["luftreiniger", "luftbefeuchter"],
  },
  {
    slug: "wassersieder-kochfelder",
    amazonCategoryId: "kitchen",
    nameDe: "Kochen & Zubereiten",
    nameEn: "Cooking & Prep",
    descriptionDe: "Mixer, Airfryer und Zubereitungshelfer im Vergleich.",
    descriptionEn: "Blenders, air fryers and prep helpers compared.",
    searchKeywords: ["heissluftfritteuse", "standmixer"],
  },
  {
    slug: "kindermode",
    amazonCategoryId: "fashion",
    nameDe: "Kindermode",
    nameEn: "Kids' Fashion",
    descriptionDe: "Kindermode und Basics für den Alltag.",
    descriptionEn: "Kids' fashion and everyday basics.",
    searchKeywords: ["kinderschuhe", "kindermode"],
  },
];

export function isDeniedAmazonCategoryId(id?: string | null) {
  if (!id) return true;
  return AMAZON_CATEGORY_DENYLIST.has(id.trim().toLowerCase());
}

export function normalizeAmazonCategoryName(name: string) {
  return name
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/&/g, " und ")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}
