/**
 * Curated pool of Ratgeber topics — knowledge-magazine / how-to style
 * (e.g. “How do I clean AirPods properly?”), not classic buying guides.
 *
 * Each day the cron picks one unused topic (by Article.topicKey).
 * Do not reuse static niche `/ratgeber/*` slugs from bluetooth-headphones.
 */

export type AdviceGuideTopic = {
  /** Stable identity + public slug under /ratgeber/[slug] */
  topicKey: string;
  titleDe: string;
  titleEn: string;
  keywordDe: string;
  keywordEn: string;
  audienceDe: string;
  audienceEn: string;
  /** Optional related Category.slug for soft product embeds */
  categorySlug?: string | null;
  /** Higher = preferred earlier in the backlog */
  priority?: number;
};

/** Static niche pages already served without DB — exclude from auto-generation. */
export const RESERVED_RATGEBER_SLUGS = new Set([
  "bluetooth-kopfhoerer-mit-noise-cancelling",
  "bluetooth-in-ear-kopfhoerer",
  "bluetooth-kopfhoerer-sport",
  "guenstige-bluetooth-kopfhoerer",
  "bluetooth-kopfhoerer-fuer-iphone",
  "bluetooth-kopfhoerer-buero-homeoffice",
  "bluetooth-kopfhoerer-akku-vergleich",
  "over-ear-bluetooth-kopfhoerer",
  "bluetooth-kopfhoerer-kaufberatung",
]);

export const ADVICE_GUIDE_TOPICS: AdviceGuideTopic[] = [
  {
    topicKey: "airpods-richtig-reinigen",
    titleDe: "AirPods richtig reinigen: So bleibst du schadenfrei",
    titleEn: "How to clean AirPods properly without damaging them",
    keywordDe: "AirPods reinigen",
    keywordEn: "how to clean AirPods",
    audienceDe: "AirPods-Nutzer mit Ohrenschmalz, Schweiß oder Ladecase-Schmutz",
    audienceEn: "AirPods users dealing with wax, sweat or dirty cases",
    categorySlug: "kopfhoerer",
    priority: 100,
  },
  {
    topicKey: "kaffeevollautomat-entkalken-anleitung",
    titleDe: "Kaffeevollautomat entkalken: Schritt für Schritt",
    titleEn: "Descaling a bean-to-cup machine: step by step",
    keywordDe: "Kaffeevollautomat entkalken",
    keywordEn: "how to descale coffee machine",
    audienceDe: "Vollautomaten-Besitzer mit hartem Wasser oder Warnmeldung",
    audienceEn: "Bean-to-cup owners seeing a descaling warning",
    categorySlug: "kaffeemaschinen",
    priority: 99,
  },
  {
    topicKey: "roboterstaubsauger-richtig-warten",
    titleDe: "Roboterstaubsauger warten: Filter, Bürsten, Sensoren",
    titleEn: "Robot vacuum maintenance: filters, brushes and sensors",
    keywordDe: "Roboterstaubsauger reinigen warten",
    keywordEn: "robot vacuum maintenance cleaning",
    audienceDe: "Haushalte, deren Saugroboter plötzlich schlechter putzt",
    audienceEn: "Homes where the robot suddenly cleans worse",
    categorySlug: "staubsauger",
    priority: 98,
  },
  {
    topicKey: "waschmaschine-richtig-reinigen",
    titleDe: "Waschmaschine reinigen: Trommel, Dichtung und Schublade",
    titleEn: "How to clean a washing machine: drum, seal and drawer",
    keywordDe: "Waschmaschine reinigen",
    keywordEn: "how to clean washing machine",
    audienceDe: "Haushalte mit Geruch oder Rückständen in der Maschine",
    audienceEn: "Households fighting odours or residue in the washer",
    categorySlug: "haushalt",
    priority: 97,
  },
  {
    topicKey: "laptop-akku-richtig-pflegen",
    titleDe: "Laptop-Akku schonen: Laden, Wärme und Alltagstipps",
    titleEn: "How to care for a laptop battery: charging and heat",
    keywordDe: "Laptop Akku pflegen",
    keywordEn: "laptop battery care tips",
    audienceDe: "Notebook-Nutzer, deren Laufzeit spürbar sinkt",
    audienceEn: "Notebook users noticing shorter battery life",
    categorySlug: "computer-zubehoer",
    priority: 96,
  },
  {
    topicKey: "smartphone-display-richtig-putzen",
    titleDe: "Smartphone-Display putzen: ohne Kratzer und Schlieren",
    titleEn: "How to clean a phone screen without scratches",
    keywordDe: "Handy Display reinigen",
    keywordEn: "how to clean phone screen",
    audienceDe: "Smartphones mit Fettfilm, Fingerabdrücken oder Desinfektionszwang",
    audienceEn: "Phones covered in fingerprints or needing a safe wipe-down",
    categorySlug: "smartphones",
    priority: 95,
  },
  {
    topicKey: "kopfhoerer-ohrpolster-reinigen",
    titleDe: "Kopfhörer-Ohrpolster reinigen und länger halten",
    titleEn: "How to clean headphone ear pads and make them last",
    keywordDe: "Kopfhörer Polster reinigen",
    keywordEn: "clean headphone ear pads",
    audienceDe: "Over-Ear-Nutzer mit Schweiß, Make-up oder Abnutzung",
    audienceEn: "Over-ear users dealing with sweat, makeup or wear",
    categorySlug: "bluetooth-kopfhoerer",
    priority: 94,
  },
  {
    topicKey: "airfryer-richtig-reinigen",
    titleDe: "Heißluftfritteuse reinigen: Korb, Heizspirale, Gerüche",
    titleEn: "How to clean an air fryer: basket, heater and smells",
    keywordDe: "Heißluftfritteuse reinigen",
    keywordEn: "how to clean air fryer",
    audienceDe: "Airfryer-Besitzer nach fettigen Gerichten",
    audienceEn: "Air fryer owners after greasy cooks",
    categorySlug: "kuechengeraete",
    priority: 93,
  },
  {
    topicKey: "matratze-richtig-reinigen-drehen",
    titleDe: "Matratze reinigen und drehen: Frische ohne Chemie-Overkill",
    titleEn: "How to clean and rotate a mattress the right way",
    keywordDe: "Matratze reinigen",
    keywordEn: "how to clean mattress",
    audienceDe: "Schlafzimmer mit Flecken, Geruch oder eingeliegenen Stellen",
    audienceEn: "Bedrooms with stains, odours or sagging spots",
    categorySlug: "matratzen",
    priority: 92,
  },
  {
    topicKey: "fernseher-bildschirm-richtig-putzen",
    titleDe: "TV-Bildschirm putzen: ohne Streifen und Mikrofaserschäden",
    titleEn: "How to clean a TV screen without streaks or damage",
    keywordDe: "Fernseher Bildschirm reinigen",
    keywordEn: "how to clean TV screen",
    audienceDe: "Wohnzimmer-TVs mit Staub, Fingerabdrücken oder Kindern",
    audienceEn: "Living-room TVs with dust, fingerprints or kids",
    categorySlug: "heimkino-tv",
    priority: 91,
  },
  {
    topicKey: "bluetooth-kopfhoerer-akku-schonung",
    titleDe: "Bluetooth-Kopfhörer: Akku länger fit halten",
    titleEn: "How to keep Bluetooth headphone batteries healthier longer",
    keywordDe: "Bluetooth Kopfhörer Akku schonen",
    keywordEn: "Bluetooth headphones battery care",
    audienceDe: "In-Ears und Over-Ears, die schnell leer sind",
    audienceEn: "In-ears and over-ears that drain too fast",
    categorySlug: "bluetooth-kopfhoerer",
    priority: 90,
  },
  {
    topicKey: "staubsaugerbeutel-richtig-wechseln",
    titleDe: "Staubsaugerbeutel wechseln und Filter pflegen",
    titleEn: "How to change vacuum bags and care for filters",
    keywordDe: "Staubsaugerbeutel wechseln",
    keywordEn: "change vacuum cleaner bag",
    audienceDe: "Haushalte mit Beutelstaubsauger und nachlassender Saugkraft",
    audienceEn: "Homes with bagged vacuums losing suction",
    categorySlug: "staubsauger",
    priority: 89,
  },
  {
    topicKey: "geschirrspueler-richtig-pflegen",
    titleDe: "Geschirrspüler pflegen: Salz, Klarspüler, Filter",
    titleEn: "Dishwasher care: salt, rinse aid and filters",
    keywordDe: "Geschirrspüler reinigen pflegen",
    keywordEn: "dishwasher cleaning maintenance",
    audienceDe: "Küchen mit Kalkflecken oder muffigem Spüler",
    audienceEn: "Kitchens with cloudy glasses or a musty dishwasher",
    categorySlug: "haushalt",
    priority: 88,
  },
  {
    topicKey: "powerbank-richtig-lagern-laden",
    titleDe: "Powerbank richtig laden und lagern",
    titleEn: "How to charge and store a power bank correctly",
    keywordDe: "Powerbank laden lagern",
    keywordEn: "power bank charging storage tips",
    audienceDe: "Reisende und Pendler mit Powerbanks in der Schublade",
    audienceEn: "Travelers and commuters with idle power banks",
    categorySlug: "powerbanks",
    priority: 87,
  },
  {
    topicKey: "externe-ssd-sicher-nutzen",
    titleDe: "Externe SSD sicher nutzen: Auswerfen, Kabel, Hitze",
    titleEn: "Using an external SSD safely: eject, cables and heat",
    keywordDe: "externe SSD richtig nutzen",
    keywordEn: "external SSD safe use tips",
    audienceDe: "Nutzer mit Backups und großen Dateiübertragungen",
    audienceEn: "Users doing backups and large file transfers",
    categorySlug: "speicher",
    priority: 86,
  },
  {
    topicKey: "wlan-router-richtig-aufstellen",
    titleDe: "WLAN-Router richtig aufstellen: Reichweite ohne Magie",
    titleEn: "Where to place your Wi‑Fi router for better coverage",
    keywordDe: "WLAN Router aufstellen",
    keywordEn: "where to place wifi router",
    audienceDe: "Wohnungen mit Funklöchern und Streaming-Rucklern",
    audienceEn: "Homes with dead zones and buffering streams",
    categorySlug: "netzwerk",
    priority: 85,
  },
  {
    topicKey: "rasierer-klingen-richtig-pflegen",
    titleDe: "Rasierer und Klingen pflegen: länger scharf, weniger Hautreizung",
    titleEn: "Razor and blade care: stay sharp, irritate less",
    keywordDe: "Rasierer reinigen pflegen",
    keywordEn: "razor blade cleaning care",
    audienceDe: "Nass- und Elektrorasierer-Nutzer",
    audienceEn: "Wet-shave and electric razor users",
    categorySlug: "pflege",
    priority: 84,
  },
  {
    topicKey: "zahnbuerste-aufsaetze-wechseln-hygiene",
    titleDe: "Elektrische Zahnbürste: Aufsätze wechseln und hygienisch halten",
    titleEn: "Electric toothbrush heads: when to replace and keep clean",
    keywordDe: "Zahnbürstenaufsatz wechseln",
    keywordEn: "replace electric toothbrush head",
    audienceDe: "Nutzer elektrischer Zahnbürsten",
    audienceEn: "Electric toothbrush owners",
    categorySlug: "mundpflege",
    priority: 83,
  },
  {
    topicKey: "haartrockner-filter-reinigen",
    titleDe: "Föhn-Filter reinigen: mehr Power, weniger Hitze-Stress",
    titleEn: "How to clean a hair dryer filter for better airflow",
    keywordDe: "Haartrockner Filter reinigen",
    keywordEn: "clean hair dryer filter",
    audienceDe: "Föhn-Nutzer mit schwächerem Luftstrom",
    audienceEn: "Hair dryer users noticing weaker airflow",
    categorySlug: "haarstyling",
    priority: 82,
  },
  {
    topicKey: "luftreiniger-filter-wechseln",
    titleDe: "Luftreiniger-Filter wechseln und Gerät sauber halten",
    titleEn: "How to change air purifier filters and keep the unit clean",
    keywordDe: "Luftreiniger Filter wechseln",
    keywordEn: "change air purifier filter",
    audienceDe: "Allergiker und Stadtwohnungen mit HEPA-Geräten",
    audienceEn: "Allergy sufferers and city homes with HEPA units",
    categorySlug: "klima",
    priority: 81,
  },
  {
    topicKey: "luftbefeuchter-richtig-reinigen",
    titleDe: "Luftbefeuchter reinigen: Kalk und Keime vermeiden",
    titleEn: "How to clean a humidifier and avoid scale or mould",
    keywordDe: "Luftbefeuchter reinigen",
    keywordEn: "how to clean humidifier",
    audienceDe: "Winterhaushalte mit Ultraschall- oder Verdunster-Geräten",
    audienceEn: "Winter households running ultrasonic or evaporative units",
    categorySlug: "klima",
    priority: 80,
  },
  {
    topicKey: "kindersitz-richtig-reinigen",
    titleDe: "Kindersitz reinigen: Bezug, Gurte und Schaumstoff",
    titleEn: "How to clean a car seat: cover, harness and foam",
    keywordDe: "Kindersitz reinigen",
    keywordEn: "how to clean car seat",
    audienceDe: "Eltern nach Crumbs, Milch und Saftflecken",
    audienceEn: "Parents dealing with crumbs, milk and juice stains",
    categorySlug: "baby-kind",
    priority: 79,
  },
  {
    topicKey: "kinderwagen-richtig-pflegen",
    titleDe: "Kinderwagen pflegen: Räder, Gelenke, Stoff",
    titleEn: "Stroller care: wheels, joints and fabrics",
    keywordDe: "Kinderwagen reinigen pflegen",
    keywordEn: "stroller cleaning maintenance",
    audienceDe: "Familien mit Stadt- und Gelände-Kinderwagen",
    audienceEn: "Families with city and all-terrain strollers",
    categorySlug: "baby-kind",
    priority: 78,
  },
  {
    topicKey: "hundebett-richtig-waschen",
    titleDe: "Hundebett waschen: Gerüche raus, Form behalten",
    titleEn: "How to wash a dog bed without wrecking the fill",
    keywordDe: "Hundebett waschen",
    keywordEn: "how to wash dog bed",
    audienceDe: "Hundehalter mit Haaren, Matsch und Geruch",
    audienceEn: "Dog owners fighting hair, mud and smells",
    categorySlug: "haustier",
    priority: 77,
  },
  {
    topicKey: "katzenstreu-box-richtig-reinigen",
    titleDe: "Katzentoilette richtig reinigen und Gerüche stoppen",
    titleEn: "How to clean a litter box and cut the smell",
    keywordDe: "Katzentoilette reinigen",
    keywordEn: "how to clean litter box",
    audienceDe: "Katzenhaushalte mit Geruchsproblemen",
    audienceEn: "Cat homes battling litter box odour",
    categorySlug: "haustier",
    priority: 76,
  },
  {
    topicKey: "laufschuhe-richtig-waschen-trocknen",
    titleDe: "Laufschuhe waschen und trocknen ohne Kleberschäden",
    titleEn: "How to wash and dry running shoes safely",
    keywordDe: "Laufschuhe waschen",
    keywordEn: "how to wash running shoes",
    audienceDe: "Läufer mit schlammigen oder schweißigen Schuhen",
    audienceEn: "Runners with muddy or sweaty shoes",
    categorySlug: "sport",
    priority: 75,
  },
  {
    topicKey: "yogamatte-richtig-reinigen",
    titleDe: "Yogamatte reinigen: Grip behalten, Bakterien reduzieren",
    titleEn: "How to clean a yoga mat without killing the grip",
    keywordDe: "Yogamatte reinigen",
    keywordEn: "how to clean yoga mat",
    audienceDe: "Studio- und Home-Yoga-Praktizierende",
    audienceEn: "Studio and home yoga practitioners",
    categorySlug: "sport",
    priority: 74,
  },
  {
    topicKey: "wanderschuhe-impregrieren-pflegen",
    titleDe: "Wanderschuhe imprägnieren und pflegen",
    titleEn: "How to waterproof and care for hiking boots",
    keywordDe: "Wanderschuhe imprägnieren",
    keywordEn: "waterproof hiking boots care",
    audienceDe: "Wanderer vor der Saison oder nach Nässe",
    audienceEn: "Hikers before season or after wet trails",
    categorySlug: "outdoor",
    priority: 73,
  },
  {
    topicKey: "schlaf sack-richtig-waschen",
    titleDe: "Schlafsack waschen: Daune und Kunstfaser richtig",
    titleEn: "How to wash a sleeping bag: down and synthetic",
    keywordDe: "Schlafsack waschen",
    keywordEn: "how to wash sleeping bag",
    audienceDe: "Camper und Trekking-Fans",
    audienceEn: "Campers and trekkers",
    categorySlug: "outdoor",
    priority: 72,
  },
  {
    topicKey: "bohrmaschine-richtig-reinigen-lagern",
    titleDe: "Bohrmaschine reinigen und lagern",
    titleEn: "How to clean and store a drill",
    keywordDe: "Bohrmaschine pflegen",
    keywordEn: "drill cleaning storage",
    audienceDe: "Heimwerker nach Beton- und Holzprojekten",
    audienceEn: "DIYers after concrete and wood projects",
    categorySlug: "werkzeug",
    priority: 71,
  },
  {
    topicKey: "akkuschrauber-akku-richtig-laden",
    titleDe: "Akkuschrauber-Akku laden und lagern",
    titleEn: "How to charge and store cordless drill batteries",
    keywordDe: "Akkuschrauber Akku laden",
    keywordEn: "cordless drill battery care",
    audienceDe: "Werkstatt- und Hobby-Heimwerker",
    audienceEn: "Workshop and hobby DIYers",
    categorySlug: "werkzeug",
    priority: 70,
  },
  {
    topicKey: "monitor-richtig-einstellen-augen",
    titleDe: "Monitor einstellen gegen müde Augen",
    titleEn: "How to set up a monitor to reduce eye strain",
    keywordDe: "Monitor einstellen Augen",
    keywordEn: "monitor setup eye strain",
    audienceDe: "Homeoffice und Gaming mit langen Sessions",
    audienceEn: "Home-office and gaming with long sessions",
    categorySlug: "monitore",
    priority: 69,
  },
  {
    topicKey: "buerostuhl-richtig-einstellen",
    titleDe: "Bürostuhl richtig einstellen: Höhe, Lordose, Armlehnen",
    titleEn: "How to adjust an office chair: height, lumbar, arms",
    keywordDe: "Bürostuhl einstellen",
    keywordEn: "adjust office chair ergonomics",
    audienceDe: "Schreibtisch-Arbeiter mit Rückenbeschwerden",
    audienceEn: "Desk workers with back discomfort",
    categorySlug: "buero",
    priority: 68,
  },
  {
    topicKey: "schreibtischlampe-richtig-platzieren",
    titleDe: "Schreibtischlampe richtig platzieren gegen Schatten",
    titleEn: "How to place a desk lamp to avoid glare and shadows",
    keywordDe: "Schreibtischlampe platzieren",
    keywordEn: "desk lamp placement tips",
    audienceDe: "Homeoffice und Lernplätze",
    audienceEn: "Home offices and study desks",
    categorySlug: "buero",
    priority: 67,
  },
  {
    topicKey: "wasserkocher-entkalken-anleitung",
    titleDe: "Wasserkocher entkalken: Hausmittel und Intervalle",
    titleEn: "How to descale a kettle: methods and intervals",
    keywordDe: "Wasserkocher entkalken",
    keywordEn: "how to descale kettle",
    audienceDe: "Haushalte mit hartem Leitungswasser",
    audienceEn: "Homes with hard tap water",
    categorySlug: "kuechengeraete",
    priority: 66,
  },
  {
    topicKey: "toastofen-richtig-reinigen",
    titleDe: "Mini-Backofen / Toastofen reinigen",
    titleEn: "How to clean a toaster oven",
    keywordDe: "Toastofen reinigen",
    keywordEn: "clean toaster oven",
    audienceDe: "Kleine Küchen mit Krümeln und Fettfilm",
    audienceEn: "Small kitchens with crumbs and grease film",
    categorySlug: "kuechengeraete",
    priority: 65,
  },
  {
    topicKey: "standmixer-richtig-reinigen",
    titleDe: "Standmixer reinigen: Behälter, Messer, Deckel",
    titleEn: "How to clean a blender: jar, blades and lid",
    keywordDe: "Mixer reinigen",
    keywordEn: "how to clean blender",
    audienceDe: "Smoothie- und Suppen-Fans",
    audienceEn: "Smoothie and soup makers",
    categorySlug: "kuechengeraete",
    priority: 64,
  },
  {
    topicKey: "dashcam-richtig-einrichten",
    titleDe: "Dashcam einrichten: Blickwinkel, Loop, Strom",
    titleEn: "How to set up a dash cam: angle, loop and power",
    keywordDe: "Dashcam einrichten",
    keywordEn: "dash cam setup guide",
    audienceDe: "Autofahrer vor dem ersten Einsatz",
    audienceEn: "Drivers before first install",
    categorySlug: "auto",
    priority: 63,
  },
  {
    topicKey: "autoladegeraet-richtig-nutzen",
    titleDe: "USB-C-Autoladegerät richtig nutzen ohne Handy-Hitze",
    titleEn: "Using a USB‑C car charger without overheating your phone",
    keywordDe: "Autoladegerät richtig nutzen",
    keywordEn: "USB-C car charger tips",
    audienceDe: "Pendler mit Navigation und Schnellladen",
    audienceEn: "Commuters navigating and fast-charging",
    categorySlug: "auto",
    priority: 62,
  },
  {
    topicKey: "kamera-sensor-richtig-reinigen",
    titleDe: "Kamerasensor vorsichtig reinigen – was du darfst",
    titleEn: "How to clean a camera sensor carefully",
    keywordDe: "Kamerasensor reinigen",
    keywordEn: "clean camera sensor",
    audienceDe: "Fotografie-Einsteiger mit Staubflecken auf Fotos",
    audienceEn: "Photography beginners seeing dust spots",
    categorySlug: "kameras",
    priority: 61,
  },
  {
    topicKey: "gaming-headset-polster-reinigen",
    titleDe: "Gaming-Headset reinigen: Mikrofonschutz und Polster",
    titleEn: "How to clean a gaming headset: mic and ear cushions",
    keywordDe: "Gaming Headset reinigen",
    keywordEn: "clean gaming headset",
    audienceDe: "Gamer mit langen Sessions und Schweiß",
    audienceEn: "Gamers after long sweaty sessions",
    categorySlug: "gaming",
    priority: 60,
  },
  {
    topicKey: "bluetooth-lautsprecher-wasserdicht-pflegen",
    titleDe: "Bluetooth-Lautsprecher nach Strand & Pool pflegen",
    titleEn: "Caring for a Bluetooth speaker after beach or pool",
    keywordDe: "Bluetooth Lautsprecher pflegen",
    keywordEn: "Bluetooth speaker waterproof care",
    audienceDe: "Outdoor-Partys und Urlaubsboxen",
    audienceEn: "Outdoor parties and travel speakers",
    categorySlug: "lautsprecher",
    priority: 59,
  },
  {
    topicKey: "e-bike-akku-richtig-lagern",
    titleDe: "E-Bike-Akku lagern und laden im Winter",
    titleEn: "How to store and charge an e-bike battery in winter",
    keywordDe: "E-Bike Akku lagern",
    keywordEn: "e-bike battery storage winter",
    audienceDe: "E-Bike-Fahrer in der kalten Jahreszeit",
    audienceEn: "E-bike riders in the cold season",
    categorySlug: "fahrrad",
    priority: 58,
  },
  {
    topicKey: "regenschirm-richtig-trocknen",
    titleDe: "Regenschirm richtig trocknen und lagern",
    titleEn: "How to dry and store an umbrella so it lasts",
    keywordDe: "Regenschirm trocknen",
    keywordEn: "dry store umbrella",
    audienceDe: "Alltags-Pendler bei Dauerregen",
    audienceEn: "Daily commuters in rainy seasons",
    categorySlug: null,
    priority: 57,
  },
  {
    topicKey: "daunenjacke-richtig-waschen",
    titleDe: "Daunenjacke waschen: Bäusche wiederbekommen",
    titleEn: "How to wash a down jacket and restore loft",
    keywordDe: "Daunenjacke waschen",
    keywordEn: "how to wash down jacket",
    audienceDe: "Outdoor-Kleidung nach einer Saison Dreck",
    audienceEn: "Outdoor wear after a dirty season",
    categorySlug: "bekleidung",
    priority: 56,
  },
  {
    topicKey: "handtuecher-richtig-waschen-weich",
    titleDe: "Handtücher waschen: saugfähig und ohne Fussel",
    titleEn: "How to wash towels so they stay absorbent",
    keywordDe: "Handtücher waschen saugfähig",
    keywordEn: "wash towels keep absorbent",
    audienceDe: "Haushalte mit steifen oder riechenden Handtüchern",
    audienceEn: "Homes with stiff or smelly towels",
    categorySlug: "heimtextilien",
    priority: 55,
  },
  {
    topicKey: "bettwaesche-richtig-waschen-trocknen",
    titleDe: "Bettwäsche richtig waschen und trocknen",
    titleEn: "How to wash and dry bed linen properly",
    keywordDe: "Bettwäsche waschen",
    keywordEn: "wash bed sheets properly",
    audienceDe: "Schlafzimmer-Routine und Allergiker",
    audienceEn: "Bedroom routines and allergy sufferers",
    categorySlug: "heimtextilien",
    priority: 54,
  },
  {
    topicKey: "led-deckenlampe-richtig-reinigen",
    titleDe: "LED-Deckenlampe reinigen ohne Strom-Schock",
    titleEn: "How to clean an LED ceiling light safely",
    keywordDe: "Deckenlampe reinigen",
    keywordEn: "clean ceiling light LED",
    audienceDe: "Wohnzimmer und Küche mit Staubringen am Glas",
    audienceEn: "Living rooms and kitchens with dusty shades",
    categorySlug: "beleuchtung",
    priority: 53,
  },
  {
    topicKey: "drucker-duesen-richtig-reinigen",
    titleDe: "Drucker-Düsen reinigen bei streifigen Ausdrucken",
    titleEn: "How to clean printer nozzles when prints streak",
    keywordDe: "Drucker Düsen reinigen",
    keywordEn: "clean printer nozzles",
    audienceDe: "Homeoffice mit selten genutztem Tintendrucker",
    audienceEn: "Home offices with rarely used inkjet printers",
    categorySlug: "drucker",
    priority: 52,
  },
  {
    topicKey: "smartwatch-richtig-reinigen",
    titleDe: "Smartwatch und Armband reinigen nach Sport",
    titleEn: "How to clean a smartwatch and band after workouts",
    keywordDe: "Smartwatch reinigen",
    keywordEn: "clean smartwatch band",
    audienceDe: "Fitness-Tracker und Sportuhren-Träger",
    audienceEn: "Fitness tracker and sports watch wearers",
    categorySlug: "wearables",
    priority: 51,
  },
  {
    topicKey: "fitness-tracker-hautvertraeglich-tragen",
    titleDe: "Fitness-Tracker tragen ohne Hautreizung",
    titleEn: "Wearing a fitness tracker without skin irritation",
    keywordDe: "Fitness Tracker Hautreizung",
    keywordEn: "fitness tracker skin irritation",
    audienceDe: "Träger mit Rötungen unter dem Band",
    audienceEn: "Wearers with redness under the strap",
    categorySlug: "wearables",
    priority: 50,
  },
  {
    topicKey: "koffer-richtig-packen-handgepaeck",
    titleDe: "Handgepäck richtig packen: Gewicht, Flüssigkeiten, Ordnung",
    titleEn: "How to pack cabin luggage: weight, liquids, order",
    keywordDe: "Handgepäck packen",
    keywordEn: "how to pack carry on luggage",
    audienceDe: "Kurzreisende und Viel-Flieger",
    audienceEn: "Short-trip travellers and frequent flyers",
    categorySlug: "reisegepaeck",
    priority: 49,
  },
  {
    topicKey: "campingkocher-sicher-reinigen",
    titleDe: "Campingkocher reinigen und sicher verstauen",
    titleEn: "How to clean and store a camping stove safely",
    keywordDe: "Campingkocher reinigen",
    keywordEn: "clean camping stove",
    audienceDe: "Camper nach Wochenendtrips",
    audienceEn: "Campers after weekend trips",
    categorySlug: "outdoor",
    priority: 48,
  },
  {
    topicKey: "hanteln-richtig-reinigen-lagern",
    titleDe: "Hanteln reinigen und Rost vermeiden",
    titleEn: "How to clean dumbbells and prevent rust",
    keywordDe: "Hanteln reinigen",
    keywordEn: "clean dumbbells",
    audienceDe: "Home-Gym mit Schweiß auf Metallgriffen",
    audienceEn: "Home gyms with sweaty metal grips",
    categorySlug: "sport",
    priority: 47,
  },
  {
    topicKey: "nasenhaartrimmer-hygienisch-reinigen",
    titleDe: "Nasenhaartrimmer hygienisch reinigen",
    titleEn: "How to clean a nose hair trimmer hygienically",
    keywordDe: "Nasenhaartrimmer reinigen",
    keywordEn: "clean nose hair trimmer",
    audienceDe: "Pflege-Routine im Badezimmer",
    audienceEn: "Bathroom grooming routines",
    categorySlug: "pflege",
    priority: 46,
  },
  {
    topicKey: "soundbar-richtig-aufstellen",
    titleDe: "Soundbar richtig aufstellen und einmessen",
    titleEn: "How to place and set up a soundbar",
    keywordDe: "Soundbar aufstellen",
    keywordEn: "soundbar placement setup",
    audienceDe: "Wohnzimmer mit TV und Echo-Problemen",
    audienceEn: "Living rooms with TV echo issues",
    categorySlug: "heimkino-tv",
    priority: 45,
  },
  {
    topicKey: "smart-home-geraete-sicher-einrichten",
    titleDe: "Smart-Home-Geräte sicher einrichten: WLAN, Updates, Gäste",
    titleEn: "Setting up smart home devices securely",
    keywordDe: "Smart Home sicher einrichten",
    keywordEn: "secure smart home setup",
    audienceDe: "Einsteiger mit Steckdosen, Lampen und Kameras",
    audienceEn: "Beginners with plugs, lights and cameras",
    categorySlug: "smart-home",
    priority: 44,
  },
  {
    topicKey: "mesh-wlan-richtig-platzieren",
    titleDe: "Mesh-WLAN-Knoten richtig platzieren",
    titleEn: "How to place mesh Wi‑Fi nodes for coverage",
    keywordDe: "Mesh WLAN platzieren",
    keywordEn: "mesh wifi node placement",
    audienceDe: "Mehrzimmer-Wohnungen mit Lücken",
    audienceEn: "Multi-room homes with coverage gaps",
    categorySlug: "netzwerk",
    priority: 43,
  },
  {
    topicKey: "spielecontroller-richtig-reinigen",
    titleDe: "Controller reinigen: Sticks, Tasten, Drift vorbeugen",
    titleEn: "How to clean a game controller and reduce stick drift",
    keywordDe: "Controller reinigen",
    keywordEn: "clean game controller",
    audienceDe: "Konsolen- und PC-Gamer",
    audienceEn: "Console and PC gamers",
    categorySlug: "gaming",
    priority: 42,
  },
  {
    topicKey: "tablet-display-und-huelle-pflegen",
    titleDe: "Tablet pflegen: Display, Hülle, Ladebuchse",
    titleEn: "Tablet care: screen, case and charging port",
    keywordDe: "Tablet reinigen pflegen",
    keywordEn: "tablet cleaning care tips",
    audienceDe: "Familien-Tablets und Homeoffice",
    audienceEn: "Family tablets and home offices",
    categorySlug: "tablets",
    priority: 41,
  },
  {
    topicKey: "kaffeemuehle-richtig-reinigen",
    titleDe: "Kaffeemühle reinigen: Öle und Altgeschmack weg",
    titleEn: "How to clean a coffee grinder and remove old oils",
    keywordDe: "Kaffeemühle reinigen",
    keywordEn: "clean coffee grinder",
    audienceDe: "Filter- und Espresso-Fans zu Hause",
    audienceEn: "Home filter and espresso drinkers",
    categorySlug: "kaffeemaschinen",
    priority: 40,
  },
];

export function getAdviceGuideTopic(topicKey: string): AdviceGuideTopic | null {
  return ADVICE_GUIDE_TOPICS.find((t) => t.topicKey === topicKey) ?? null;
}

export function listAdviceGuideTopics(): AdviceGuideTopic[] {
  return [...ADVICE_GUIDE_TOPICS]
    .filter((t) => !RESERVED_RATGEBER_SLUGS.has(t.topicKey))
    .sort((a, b) => (b.priority ?? 0) - (a.priority ?? 0));
}
