/**
 * Curated pool of Ratgeber topics. Each day the cron picks one unused topic
 * (by Article.topicKey) and generates a long-form advice guide.
 *
 * Do not reuse static niche `/ratgeber/*` slugs from bluetooth-headphones.
 */

export type AdviceGuideTopic = {
  /** Stable identity + public slug under /ratgeber/[slug] */
  topicKey: string;
  titleDe: string;
  titleEn: string;
  keywordDe: string;
  keywordEn: string;
  audienceDe: string;
  audienceEn: string;
  /** Optional related Category.slug for product embeds */
  categorySlug?: string | null;
  /** Higher = preferred earlier in the backlog */
  priority?: number;
};

/** Static niche pages already served without DB — exclude from auto-generation. */
export const RESERVED_RATGEBER_SLUGS = new Set([
  "bluetooth-kopfhoerer-mit-noise-cancelling",
  "bluetooth-in-ear-kopfhoerer",
  "bluetooth-kopfhoerer-sport",
  "guenstige-bluetooth-kopfhoerer",
  "bluetooth-kopfhoerer-fuer-iphone",
  "bluetooth-kopfhoerer-buero-homeoffice",
  "bluetooth-kopfhoerer-akku-vergleich",
  "over-ear-bluetooth-kopfhoerer",
  "bluetooth-kopfhoerer-kaufberatung",
]);

export const ADVICE_GUIDE_TOPICS: AdviceGuideTopic[] = [
  {
    topicKey: "kaffeevollautomat-kaufberatung",
    titleDe: "Kaffeevollautomat kaufen: Worauf es wirklich ankommt",
    titleEn: "Buying a bean-to-cup machine: what actually matters",
    keywordDe: "Kaffeevollautomat Kaufberatung",
    keywordEn: "bean to cup coffee machine buying guide",
    audienceDe: "Kaffee-Fans, die zu Hause Barista-Qualität wollen",
    audienceEn: "Coffee fans who want café quality at home",
    categorySlug: "kaffeemaschinen",
    priority: 100,
  },
  {
    topicKey: "roboterstaubsauger-testsieger-guide",
    titleDe: "Roboterstaubsauger: So findest du den richtigen",
    titleEn: "Robot vacuums: how to pick the right one",
    keywordDe: "Roboterstaubsauger Ratgeber",
    keywordEn: "robot vacuum buying guide",
    audienceDe: "Haushalte mit wenig Zeit fürs Staubsaugen",
    audienceEn: "Busy households that want hands-off cleaning",
    categorySlug: "staubsauger",
    priority: 99,
  },
  {
    topicKey: "akku-staubsauger-laufzeit-vergleich",
    titleDe: "Akku-Staubsauger: Laufzeit, Saugkraft und Fehlkäufe",
    titleEn: "Cordless vacuums: runtime, suction and pitfalls",
    keywordDe: "Akku Staubsauger Kaufberatung",
    keywordEn: "cordless vacuum buying guide",
    audienceDe: "Mieter und Eigenheimer ohne Kabelchaos",
    audienceEn: "Renters and homeowners who hate cords",
    categorySlug: "akku-staubsauger",
    priority: 98,
  },
  {
    topicKey: "fernseher-65-zoll-kaufberatung",
    titleDe: "65-Zoll-Fernseher kaufen: Panel, HDMI und Ton",
    titleEn: "Buying a 65-inch TV: panel, HDMI and sound",
    keywordDe: "65 Zoll Fernseher Ratgeber",
    keywordEn: "65 inch TV buying guide",
    audienceDe: "Wohnzimmer-Upgrades ohne Marketing-Buzzwords",
    audienceEn: "Living-room upgrades without marketing fluff",
    categorySlug: "heimkino-tv",
    priority: 97,
  },
  {
    topicKey: "soundbar-heimkino-guide",
    titleDe: "Soundbar wählen: Dolby, Subwoofer und Aufstellung",
    titleEn: "Choosing a soundbar: Dolby, subwoofers and placement",
    keywordDe: "Soundbar Kaufberatung",
    keywordEn: "soundbar buying guide",
    audienceDe: "TV-Zuschauer mit flachem Fernseher-Sound",
    audienceEn: "TV viewers stuck with thin built-in speakers",
    categorySlug: "heimkino-tv",
    priority: 96,
  },
  {
    topicKey: "smartphone-mittelklasse-2026",
    titleDe: "Mittelklasse-Smartphone: Leistung ohne Flagship-Preis",
    titleEn: "Mid-range smartphones: performance without flagship prices",
    keywordDe: "Mittelklasse Smartphone Ratgeber",
    keywordEn: "midrange smartphone buying guide",
    audienceDe: "Alltagsnutzer mit Budget bis ca. 400 €",
    audienceEn: "Everyday users with a mid-tier budget",
    categorySlug: "smartphones",
    priority: 95,
  },
  {
    topicKey: "laptop-homeoffice-kaufberatung",
    titleDe: "Laptop fürs Homeoffice: Display, Tastatur, Akku",
    titleEn: "Home-office laptops: display, keyboard and battery",
    keywordDe: "Laptop Homeoffice Kaufberatung",
    keywordEn: "home office laptop buying guide",
    audienceDe: "Remote-Worker und Studierende",
    audienceEn: "Remote workers and students",
    categorySlug: "computer-zubehoer",
    priority: 94,
  },
  {
    topicKey: "monitor-homeoffice-guide",
    titleDe: "Büro-Monitor kaufen: Größe, Panel und Ergonomie",
    titleEn: "Office monitors: size, panel type and ergonomics",
    keywordDe: "Monitor Homeoffice Ratgeber",
    keywordEn: "office monitor buying guide",
    audienceDe: "Schreibtisch-Arbeiter mit Nackenproblemen",
    audienceEn: "Desk workers who care about posture",
    categorySlug: "computer-zubehoer",
    priority: 93,
  },
  {
    topicKey: "airfryer-heissluftfritteuse-guide",
    titleDe: "Heißluftfritteuse: Größe, Programme und Alltagstauglichkeit",
    titleEn: "Air fryers: size, programmes and everyday use",
    keywordDe: "Heißluftfritteuse Kaufberatung",
    keywordEn: "air fryer buying guide",
    audienceDe: "Kleine Haushalte und Meal-Prep-Fans",
    audienceEn: "Small households and meal-prep fans",
    categorySlug: "haushalt-kueche",
    priority: 92,
  },
  {
    topicKey: "waschmaschine-effizienz-guide",
    titleDe: "Waschmaschine kaufen: Fassungsvermögen und Effizienz",
    titleEn: "Buying a washing machine: capacity and efficiency",
    keywordDe: "Waschmaschine Kaufberatung",
    keywordEn: "washing machine buying guide",
    audienceDe: "Familien und Erstausstatter",
    audienceEn: "Families and first-time buyers",
    categorySlug: "haushalt-kueche",
    priority: 91,
  },
  {
    topicKey: "akkuschrauber-einsteiger-guide",
    titleDe: "Akkuschrauber für Einsteiger: Volt, Drehmoment, Bits",
    titleEn: "Cordless drills for beginners: volts, torque and bits",
    keywordDe: "Akkuschrauber Kaufberatung",
    keywordEn: "cordless drill buying guide",
    audienceDe: "Heimwerker ohne Profi-Ambitionen",
    audienceEn: "DIY beginners without pro ambitions",
    categorySlug: "heimwerker",
    priority: 90,
  },
  {
    topicKey: "rasenmaeher-elektro-vs-akku",
    titleDe: "Rasenmäher: Elektro, Akku oder Benzin?",
    titleEn: "Lawn mowers: electric, battery or petrol?",
    keywordDe: "Rasenmäher Kaufberatung",
    keywordEn: "lawn mower buying guide",
    audienceDe: "Gartenbesitzer mit mittelgroßem Rasen",
    audienceEn: "Garden owners with a mid-size lawn",
    categorySlug: "garten",
    priority: 89,
  },
  {
    topicKey: "fitness-tracker-vs-smartwatch",
    titleDe: "Fitness-Tracker oder Smartwatch – was lohnt sich?",
    titleEn: "Fitness tracker vs smartwatch – which is worth it?",
    keywordDe: "Fitness Tracker vs Smartwatch",
    keywordEn: "fitness tracker vs smartwatch",
    audienceDe: "Sportliche Einsteiger und Vieltelefonierer",
    audienceEn: "Casual athletes and heavy phone users",
    categorySlug: "fitness",
    priority: 88,
  },
  {
    topicKey: "laufschuhe-asphalt-guide",
    titleDe: "Laufschuhe für Asphalt: Dämpfung, Passform, Wechselrhythmus",
    titleEn: "Road running shoes: cushioning, fit and rotation",
    keywordDe: "Laufschuhe Kaufberatung",
    keywordEn: "running shoes buying guide",
    audienceDe: "Hobby-Läufer bis Halbmarathon",
    audienceEn: "Hobby runners up to half-marathon",
    categorySlug: "sport-outdoor",
    priority: 87,
  },
  {
    topicKey: "kindersitz-auto-sicherheit",
    titleDe: "Kindersitz sicher wählen: i-Size, Isofix und Alter",
    titleEn: "Choosing a child car seat: i-Size, Isofix and age",
    keywordDe: "Kindersitz Kaufberatung",
    keywordEn: "child car seat buying guide",
    audienceDe: "Eltern vor dem ersten Autokauf-Zubehör",
    audienceEn: "Parents buying their first car seat",
    categorySlug: "baby",
    priority: 86,
  },
  {
    topicKey: "kinderwagen-alltag-guide",
    titleDe: "Kinderwagen für den Alltag: Stadt, Auto, Gewicht",
    titleEn: "Everyday strollers: city use, car boots and weight",
    keywordDe: "Kinderwagen Kaufberatung",
    keywordEn: "stroller buying guide",
    audienceDe: "Eltern in Stadt und Vorstadt",
    audienceEn: "Parents in city and suburb settings",
    categorySlug: "baby",
    priority: 85,
  },
  {
    topicKey: "matratze-haertegrad-guide",
    titleDe: "Matratze finden: Härtegrad, Kern und Allergiker",
    titleEn: "Finding a mattress: firmness, core and allergies",
    keywordDe: "Matratze Kaufberatung",
    keywordEn: "mattress buying guide",
    audienceDe: "Schlaf-Optimierer und Umzügler",
    audienceEn: "Sleep optimisers and people moving home",
    categorySlug: "moebel",
    priority: 84,
  },
  {
    topicKey: "buerostuhl-ergonomie-guide",
    titleDe: "Bürostuhl mit Ergonomie: Sitztiefe, Lordose, Budget",
    titleEn: "Ergonomic office chairs: depth, lumbar and budget",
    keywordDe: "Bürostuhl Kaufberatung",
    keywordEn: "office chair buying guide",
    audienceDe: "Homeoffice-Nutzer mit langen Sitzzeiten",
    audienceEn: "Home-office users with long sitting days",
    categorySlug: "moebel",
    priority: 83,
  },
  {
    topicKey: "schreibtischlampe-homeoffice",
    titleDe: "Schreibtischlampe: Lichtfarbe, Flicker und USB",
    titleEn: "Desk lamps: colour temperature, flicker and USB",
    keywordDe: "Schreibtischlampe Ratgeber",
    keywordEn: "desk lamp buying guide",
    audienceDe: "Abendarbeiter und Studenten",
    audienceEn: "Evening workers and students",
    categorySlug: "beleuchtung",
    priority: 82,
  },
  {
    topicKey: "koffer-handgepaeck-airline",
    titleDe: "Handgepäck-Koffer: Maße, Rollen und Lock-in",
    titleEn: "Cabin luggage: sizes, wheels and airline limits",
    keywordDe: "Handgepäck Koffer Kaufberatung",
    keywordEn: "cabin suitcase buying guide",
    audienceDe: "Vielflieger und Städtetrip-Fans",
    audienceEn: "Frequent flyers and city-break travellers",
    categorySlug: "koffer-reisen",
    priority: 81,
  },
  {
    topicKey: "kamera-einsteiger-spiegelos",
    titleDe: "Systemkamera für Einsteiger: APS-C, Kit und Video",
    titleEn: "Beginner mirrorless cameras: APS-C, kits and video",
    keywordDe: "Systemkamera Einsteiger Ratgeber",
    keywordEn: "beginner mirrorless camera guide",
    audienceDe: "Hobbyfotografen, die das Smartphone verlassen",
    audienceEn: "Hobby photographers leaving the phone behind",
    categorySlug: "kameras-foto",
    priority: 80,
  },
  {
    topicKey: "dashcam-auto-datenschutz",
    titleDe: "Dashcam im Auto: Recht, Akku und Aufnahmequalität",
    titleEn: "Car dash cams: legality, power and video quality",
    keywordDe: "Dashcam Kaufberatung",
    keywordEn: "dash cam buying guide",
    audienceDe: "Autofahrer mit Fokus auf Beweissicherung",
    audienceEn: "Drivers who want incident evidence",
    categorySlug: "auto-motorrad",
    priority: 79,
  },
  {
    topicKey: "autoladegeraet-usb-c-pd",
    titleDe: "USB-C Autoladegerät: Power Delivery ohne Kabelsalat",
    titleEn: "USB-C car chargers: Power Delivery without cable mess",
    keywordDe: "USB-C Autoladegerät Ratgeber",
    keywordEn: "USB-C car charger buying guide",
    audienceDe: "Pendler mit mehreren Geräten",
    audienceEn: "Commuters with multiple devices",
    categorySlug: "auto-motorrad",
    priority: 78,
  },
  {
    topicKey: "hundebett-orthopaedisch",
    titleDe: "Orthopädisches Hundebett: Größe, Bezug, Pflege",
    titleEn: "Orthopaedic dog beds: size, cover and care",
    keywordDe: "Hundebett Kaufberatung",
    keywordEn: "dog bed buying guide",
    audienceDe: "Hundehalter mit älteren oder großen Hunden",
    audienceEn: "Dog owners with older or large dogs",
    categorySlug: "haustier",
    priority: 77,
  },
  {
    topicKey: "katzenstreu-vergleich-guide",
    titleDe: "Katzenstreu vergleichen: Klump, Silikat, Geruch",
    titleEn: "Cat litter compared: clumping, silica and odour",
    keywordDe: "Katzenstreu Ratgeber",
    keywordEn: "cat litter buying guide",
    audienceDe: "Katzenhalter mit Geruchssensibilität",
    audienceEn: "Cat owners who care about odour control",
    categorySlug: "haustier",
    priority: 76,
  },
  {
    topicKey: "elektrische-zahnbuerste-guide",
    titleDe: "Elektrische Zahnbürste: Schall, Aufsteckbürsten, Timer",
    titleEn: "Electric toothbrushes: sonic, heads and timers",
    keywordDe: "Elektrische Zahnbürste Kaufberatung",
    keywordEn: "electric toothbrush buying guide",
    audienceDe: "Alltagsnutzer mit Fokus auf Zahnfleisch",
    audienceEn: "Everyday users focused on gum health",
    categorySlug: "drogerie-koerperpflege",
    priority: 75,
  },
  {
    topicKey: "haartrockner-ionen-guide",
    titleDe: "Haartrockner mit Ionen: Hitze, Watt und Gewicht",
    titleEn: "Ionic hair dryers: heat, wattage and weight",
    keywordDe: "Haartrockner Kaufberatung",
    keywordEn: "hair dryer buying guide",
    audienceDe: "Menschen mit feinern oder lockigem Haar",
    audienceEn: "People with fine or curly hair",
    categorySlug: "beauty-pflege",
    priority: 74,
  },
  {
    topicKey: "luftreiniger-allergiker-guide",
    titleDe: "Luftreiniger für Allergiker: CADR, Filter, Lautstärke",
    titleEn: "Air purifiers for allergies: CADR, filters and noise",
    keywordDe: "Luftreiniger Allergiker Ratgeber",
    keywordEn: "air purifier allergy buying guide",
    audienceDe: "Haushalte mit Pollen- oder Tierallergie",
    audienceEn: "Homes with pollen or pet allergies",
    categorySlug: "haushalt-kueche",
    priority: 73,
  },
  {
    topicKey: "luftbefeuchter-winter-guide",
    titleDe: "Luftbefeuchter im Winter: verdunsten, verdampfen, reinigen",
    titleEn: "Winter humidifiers: evaporative vs warm mist and cleaning",
    keywordDe: "Luftbefeuchter Kaufberatung",
    keywordEn: "humidifier buying guide",
    audienceDe: "Menschen mit trockener Heizungsluft",
    audienceEn: "People dealing with dry heated air",
    categorySlug: "haushalt-kueche",
    priority: 72,
  },
  {
    topicKey: "powerbank-reisen-guide",
    titleDe: "Powerbank für Reisen: Kapazität, Flugregeln, PD",
    titleEn: "Travel power banks: capacity, airline rules and PD",
    keywordDe: "Powerbank Reise Ratgeber",
    keywordEn: "travel power bank buying guide",
    audienceDe: "Reisende mit Laptop und Smartphone",
    audienceEn: "Travellers with laptop and phone",
    categorySlug: "elektronik",
    priority: 71,
  },
  {
    topicKey: "externe-ssd-backup-guide",
    titleDe: "Externe SSD: Geschwindigkeit, Gehäuse und Backup",
    titleEn: "External SSDs: speed, enclosures and backups",
    keywordDe: "Externe SSD Kaufberatung",
    keywordEn: "external SSD buying guide",
    audienceDe: "Fotografen, Videografen und Backup-Fans",
    audienceEn: "Photographers, videographers and backup fans",
    categorySlug: "computer-zubehoer",
    priority: 70,
  },
  {
    topicKey: "wlan-router-mesh-guide",
    titleDe: "WLAN-Router und Mesh: Abdeckung ohne Funklöcher",
    titleEn: "Wi-Fi routers and mesh: coverage without dead spots",
    keywordDe: "Mesh WLAN Kaufberatung",
    keywordEn: "mesh wifi buying guide",
    audienceDe: "Mehrparteien- und Einfamilienhäuser",
    audienceEn: "Flats and family homes with weak Wi-Fi",
    categorySlug: "elektronik",
    priority: 69,
  },
  {
    topicKey: "smart-home-einstieg-guide",
    titleDe: "Smart Home Einstieg: Matter, Bridge und Sicherheit",
    titleEn: "Smart home starters: Matter, hubs and security",
    keywordDe: "Smart Home Einstieg Ratgeber",
    keywordEn: "smart home starter guide",
    audienceDe: "Technik-Interessierte ohne Vendor-Lock-Angst",
    audienceEn: "Tech-curious buyers avoiding vendor lock-in",
    categorySlug: "elektronik",
    priority: 68,
  },
  {
    topicKey: "druckerkaufen-tinte-vs-laser",
    titleDe: "Drucker kaufen: Tinte, Tank oder Laser?",
    titleEn: "Buying a printer: ink, tank or laser?",
    keywordDe: "Drucker Kaufberatung",
    keywordEn: "printer buying guide",
    audienceDe: "Homeoffice und Familien mit Schulkindern",
    audienceEn: "Home offices and families with school kids",
    categorySlug: "buerobedarf",
    priority: 67,
  },
  {
    topicKey: "gaming-headset-mikrofon-guide",
    titleDe: "Gaming-Headset: Mikrofon, Komfort und Surround",
    titleEn: "Gaming headsets: mic quality, comfort and surround",
    keywordDe: "Gaming Headset Kaufberatung",
    keywordEn: "gaming headset buying guide",
    audienceDe: "PC- und Konsolen-Spieler",
    audienceEn: "PC and console gamers",
    categorySlug: "kopfhoerer-audio",
    priority: 66,
  },
  {
    topicKey: "bluetooth-lautsprecher-outdoor",
    titleDe: "Bluetooth-Lautsprecher Outdoor: IPX, Akku, Lautstärke",
    titleEn: "Outdoor Bluetooth speakers: IPX, battery and volume",
    keywordDe: "Bluetooth Lautsprecher Outdoor",
    keywordEn: "outdoor bluetooth speaker guide",
    audienceDe: "Garten-, Strand- und Festivalgänger",
    audienceEn: "Garden, beach and festival listeners",
    categorySlug: "kopfhoerer-audio",
    priority: 65,
  },
  {
    topicKey: "e-bike-akku-pflege",
    titleDe: "E-Bike Akku richtig pflegen und Reichweite planen",
    titleEn: "E-bike battery care and planning real range",
    keywordDe: "E-Bike Akku Ratgeber",
    keywordEn: "ebike battery care guide",
    audienceDe: "Pendler und Freizeit-Radfahrer",
    audienceEn: "Commuters and leisure cyclists",
    categorySlug: "sport-outdoor",
    priority: 64,
  },
  {
    topicKey: "wanderucksack-tageswanderung",
    titleDe: "Wanderrucksack für Tageswanderungen: Volumen und Tragekomfort",
    titleEn: "Day-hike backpacks: volume and carry comfort",
    keywordDe: "Wanderrucksack Kaufberatung",
    keywordEn: "hiking daypack buying guide",
    audienceDe: "Wochenend-Wanderer",
    audienceEn: "Weekend hikers",
    categorySlug: "sport-outdoor",
    priority: 63,
  },
  {
    topicKey: "campingkocher-gas-vs-benzin",
    titleDe: "Campingkocher: Gas, Benzin oder Kartusche?",
    titleEn: "Camping stoves: gas, petrol or cartridge?",
    keywordDe: "Campingkocher Ratgeber",
    keywordEn: "camping stove buying guide",
    audienceDe: "Zelt-Camper und Vanlife",
    audienceEn: "Tent campers and vanlifers",
    categorySlug: "sport-outdoor",
    priority: 62,
  },
  {
    topicKey: "schlafsaecke-temperatur-guide",
    titleDe: "Schlafsack wählen: Komforttemperatur und Isolation",
    titleEn: "Choosing a sleeping bag: comfort rating and insulation",
    keywordDe: "Schlafsack Kaufberatung",
    keywordEn: "sleeping bag buying guide",
    audienceDe: "Camper und Trekking-Einsteiger",
    audienceEn: "Campers and trekking beginners",
    categorySlug: "sport-outdoor",
    priority: 61,
  },
  {
    topicKey: "werkzeugkoffer-einsteiger",
    titleDe: "Werkzeugkoffer für Einsteiger: Muss-Haben vs Nice-to-have",
    titleEn: "Beginner tool kits: must-haves vs nice-to-haves",
    keywordDe: "Werkzeugkoffer Kaufberatung",
    keywordEn: "tool kit buying guide",
    audienceDe: "Mieter und Erstwohnungs-Ausstatter",
    audienceEn: "Renters furnishing a first home",
    categorySlug: "heimwerker",
    priority: 60,
  },
  {
    topicKey: "bohrmaschine-schlagbohrer",
    titleDe: "Bohrmaschine oder Schlagbohrer – wann was?",
    titleEn: "Drill vs hammer drill – when to use which",
    keywordDe: "Schlagbohrer Ratgeber",
    keywordEn: "hammer drill buying guide",
    audienceDe: "Heimwerker mit Beton- und Holzprojekten",
    audienceEn: "DIYers drilling wood and masonry",
    categorySlug: "heimwerker",
    priority: 59,
  },
  {
    topicKey: "kuechenmaschine-vs-standmixer",
    titleDe: "Küchenmaschine oder Standmixer – Entscheidungshilfe",
    titleEn: "Food processor vs blender – decision guide",
    keywordDe: "Küchenmaschine vs Mixer",
    keywordEn: "food processor vs blender",
    audienceDe: "Hobbyköche mit begrenztem Platz",
    audienceEn: "Home cooks short on counter space",
    categorySlug: "haushalt-kueche",
    priority: 58,
  },
  {
    topicKey: "wasserkocher-temperaturwahl",
    titleDe: "Wasserkocher mit Temperaturwahl: Tee, Kaffee, Kalk",
    titleEn: "Variable-temperature kettles: tea, coffee and limescale",
    keywordDe: "Wasserkocher Temperaturwahl",
    keywordEn: "variable temperature kettle guide",
    audienceDe: "Tee- und Filterkaffee-Trinker",
    audienceEn: "Tea and pour-over coffee drinkers",
    categorySlug: "haushalt-kueche",
    priority: 57,
  },
  {
    topicKey: "toastofen-mini-backofen",
    titleDe: "Minibackofen: Pizza, Umluft und Energiekosten",
    titleEn: "Toaster ovens: pizza, convection and energy use",
    keywordDe: "Minibackofen Kaufberatung",
    keywordEn: "toaster oven buying guide",
    audienceDe: "Kleine Küchen und Studentenbuden",
    audienceEn: "Small kitchens and student flats",
    categorySlug: "haushalt-kueche",
    priority: 56,
  },
  {
    topicKey: "nasenhaartrimmer-pflege",
    titleDe: "Nasenhaartrimmer und Präzisionspflege ohne Verletzungen",
    titleEn: "Nose hair trimmers and safe precision grooming",
    keywordDe: "Nasenhaartrimmer Ratgeber",
    keywordEn: "nose hair trimmer buying guide",
    audienceDe: "Männer mit Fokus auf diskrete Pflege",
    audienceEn: "Men focused on discreet grooming",
    categorySlug: "beauty-pflege",
    priority: 55,
  },
  {
    topicKey: "rasierer-nass-vs-elektro",
    titleDe: "Nassrasur oder Elektrorasierer – Hauttyp entscheiden lassen",
    titleEn: "Wet shave vs electric: let skin type decide",
    keywordDe: "Rasierer Kaufberatung",
    keywordEn: "razor vs electric shaver guide",
    audienceDe: "Männer mit empfindlicher Haut",
    audienceEn: "Men with sensitive skin",
    categorySlug: "beauty-pflege",
    priority: 54,
  },
  {
    topicKey: "spielzeug-ab-3-jahren",
    titleDe: "Spielzeug ab 3 Jahren: Sicherheit, Kreativität, Haltbarkeit",
    titleEn: "Toys for ages 3+: safety, creativity and durability",
    keywordDe: "Spielzeug ab 3 Ratgeber",
    keywordEn: "toys for 3 year olds guide",
    audienceDe: "Eltern und Großeltern vor Geburtstagen",
    audienceEn: "Parents and grandparents buying gifts",
    categorySlug: "spielzeug",
    priority: 53,
  },
  {
    topicKey: "lego-aufbewahrung-sortieren",
    titleDe: "LEGO sortieren und lagern ohne Chaos",
    titleEn: "Sorting and storing LEGO without chaos",
    keywordDe: "LEGO Aufbewahrung Ratgeber",
    keywordEn: "LEGO storage guide",
    audienceDe: "Familien mit wachsendem Steine-Berg",
    audienceEn: "Families with a growing brick mountain",
    categorySlug: "spielzeug",
    priority: 52,
  },
  {
    topicKey: "uhren-smartwatch-alltag",
    titleDe: "Alltags-Smartwatch: Akkulaufzeit, Sport und Benachrichtigungen",
    titleEn: "Everyday smartwatches: battery, sport and notifications",
    keywordDe: "Smartwatch Alltag Kaufberatung",
    keywordEn: "everyday smartwatch buying guide",
    audienceDe: "Nutzer zwischen Sport und Business",
    audienceEn: "Users between sport and work life",
    categorySlug: "uhren",
    priority: 51,
  },
  {
    topicKey: "laufschuhe-trail-guide",
    titleDe: "Trailrunning-Schuhe: Grip, Schutz und Passform",
    titleEn: "Trail running shoes: grip, protection and fit",
    keywordDe: "Trailrunning Schuhe Ratgeber",
    keywordEn: "trail running shoe buying guide",
    audienceDe: "Läufer abseits asphaltierter Wege",
    audienceEn: "Runners leaving paved roads",
    categorySlug: "sport-outdoor",
    priority: 50,
  },
  {
    topicKey: "yogamatte-dicke-grip",
    titleDe: "Yogamatte wählen: Dicke, Grip und Schweiß",
    titleEn: "Choosing a yoga mat: thickness, grip and sweat",
    keywordDe: "Yogamatte Kaufberatung",
    keywordEn: "yoga mat buying guide",
    audienceDe: "Studio- und Heimyogis",
    audienceEn: "Studio and home yoga practitioners",
    categorySlug: "fitness",
    priority: 49,
  },
  {
    topicKey: "hanteln-kurzhantel-set",
    titleDe: "Kurzhantel-Set für Zuhause: Gewichtsstufen und Platz",
    titleEn: "Home dumbbell sets: increments and space",
    keywordDe: "Kurzhantel Set Ratgeber",
    keywordEn: "home dumbbell set guide",
    audienceDe: "Kraftsport-Einsteiger im Wohnzimmer",
    audienceEn: "Strength beginners training at home",
    categorySlug: "fitness",
    priority: 48,
  },
  {
    topicKey: "regenschirm-sturmfest",
    titleDe: "Sturmfeste Regenschirme: Gestänge, Bespannung, Garantie",
    titleEn: "Storm-proof umbrellas: frame, canopy and warranty",
    keywordDe: "Sturmfester Regenschirm",
    keywordEn: "storm proof umbrella guide",
    audienceDe: "Pendler bei norddeutschem Wetter",
    audienceEn: "Commuters in windy wet climates",
    categorySlug: "mode",
    priority: 47,
  },
  {
    topicKey: "winterjacke-daune-vs-synthetic",
    titleDe: "Winterjacke: Daune oder Synthetik – wann was wärmt",
    titleEn: "Winter jackets: down vs synthetic warmth",
    keywordDe: "Winterjacke Kaufberatung",
    keywordEn: "winter jacket buying guide",
    audienceDe: "Stadtmenschen und Outdoor-Fans",
    audienceEn: "City dwellers and outdoor fans",
    categorySlug: "mode",
    priority: 46,
  },
  {
    topicKey: "laufschuhe-pronationsstuetze",
    titleDe: "Laufschuhe mit Pronationsstütze – brauchst du sie wirklich?",
    titleEn: "Stability running shoes – do you really need them?",
    keywordDe: "Pronationsstütze Laufschuhe",
    keywordEn: "stability running shoes guide",
    audienceDe: "Läufer mit Überpronation-Verdacht",
    audienceEn: "Runners wondering about overpronation",
    categorySlug: "schuhe",
    priority: 45,
  },
  {
    topicKey: "wanderschuhe-wasserdicht",
    titleDe: "Wasserdichte Wanderschuhe: Membrane, Sohle, Einlaufen",
    titleEn: "Waterproof hiking boots: membranes, soles and break-in",
    keywordDe: "Wanderschuhe Kaufberatung",
    keywordEn: "hiking boots buying guide",
    audienceDe: "Mehrtageswanderer und Alpen-Wochenenden",
    audienceEn: "Multi-day hikers and alpine weekends",
    categorySlug: "schuhe",
    priority: 44,
  },
  {
    topicKey: "buerodrucker-scanner-kombi",
    titleDe: "Multifunktionsdrucker: Scan, ADF und Folgekosten",
    titleEn: "All-in-one printers: scan, ADF and running costs",
    keywordDe: "Multifunktionsdrucker Ratgeber",
    keywordEn: "all in one printer buying guide",
    audienceDe: "Kleinbüros und Homeoffice mit Papierkram",
    audienceEn: "Small offices drowning in paperwork",
    categorySlug: "buerobedarf",
    priority: 43,
  },
  {
    topicKey: "led-deckenlampe-wohnzimmer",
    titleDe: "LED-Deckenlampe Wohnzimmer: Lumen, Dimmen, Farbtemperatur",
    titleEn: "Living-room LED ceiling lights: lumens, dimming, CCT",
    keywordDe: "LED Deckenlampe Ratgeber",
    keywordEn: "LED ceiling light buying guide",
    audienceDe: "Renovierer und Mieter mit kaltem Licht",
    audienceEn: "Renovators stuck with cold lighting",
    categorySlug: "beleuchtung",
    priority: 42,
  },
  {
    topicKey: "bettwaesche-baumwolle-satin",
    titleDe: "Bettwäsche: Renforcé, Satin oder Jersey?",
    titleEn: "Bed linen: percale, satin or jersey?",
    keywordDe: "Bettwäsche Kaufberatung",
    keywordEn: "bed linen buying guide",
    audienceDe: "Schlaf-Optimierer mit Waschmaschine im Blick",
    audienceEn: "Sleep optimisers who wash weekly",
    categorySlug: "heimtextilien",
    priority: 41,
  },
  {
    topicKey: "handtuecher-saugfaehigkeit",
    titleDe: "Handtücher: Grammatur, Saugfähigkeit und Pflege",
    titleEn: "Towels: GSM, absorbency and care",
    keywordDe: "Handtücher Kaufberatung",
    keywordEn: "towel buying guide",
    audienceDe: "Haushalte vor dem Handtuch-Wechsel",
    audienceEn: "Households refreshing bathroom textiles",
    categorySlug: "heimtextilien",
    priority: 40,
  },
];

export function getAdviceGuideTopic(topicKey: string): AdviceGuideTopic | null {
  return ADVICE_GUIDE_TOPICS.find((t) => t.topicKey === topicKey) ?? null;
}

export function listAdviceGuideTopics(): AdviceGuideTopic[] {
  return [...ADVICE_GUIDE_TOPICS]
    .filter((t) => !RESERVED_RATGEBER_SLUGS.has(t.topicKey))
    .sort((a, b) => (b.priority ?? 0) - (a.priority ?? 0));
}
